In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv("Placement.csv")

In [4]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [5]:
dataset["ssc_p"].value_counts()

ssc_p
62.00    11
63.00    10
67.00     9
73.00     9
52.00     9
         ..
55.68     1
41.00     1
83.33     1
43.00     1
80.60     1
Name: count, Length: 103, dtype: int64

In [6]:
len(dataset["ssc_p"].value_counts())

103

In [7]:
freqTable = pd.DataFrame(columns = ["Unique Values","Frequency","Relative Frequency","Cusum"])
freqTable

Empty DataFrame
Columns: [Unique Values, Frequency, Relative Frequency, Cusum]
Index: []

In [8]:
freqTable["Unique Values"] = dataset["ssc_p"].value_counts().index
freqTable["Frequency"] = dataset["ssc_p"].value_counts().values
freqTable["Relative Frequency"] = (freqTable["Frequency"]/103)
freqTable["Cusum"] = freqTable["Relative Frequency"].cumsum()

In [9]:
freqTable

     Unique Values  Frequency  Relative Frequency     Cusum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [10]:
# Frequency Function
def Frequency(ColumnName,dataset):
    freqTable = pd.DataFrame(columns = ["Unique Values","Frequency","Relative Frequency","Cusum"])
    freqTable["Unique Values"] = dataset[ColumnName].value_counts().index
    freqTable["Frequency"] = dataset[ColumnName].value_counts().values
    freqTable["Relative Frequency"] = (freqTable["Frequency"]/103)
    freqTable["Cusum"] = freqTable["Relative Frequency"].cumsum()
    return freqTable

In [11]:
Frequency("ssc_p",dataset)

     Unique Values  Frequency  Relative Frequency     Cusum
0            62.00         11            0.106796  0.106796
1            63.00         10            0.097087  0.203883
2            67.00          9            0.087379  0.291262
3            73.00          9            0.087379  0.378641
4            52.00          9            0.087379  0.466019
..             ...        ...                 ...       ...
98           55.68          1            0.009709  2.048544
99           41.00          1            0.009709  2.058252
100          83.33          1            0.009709  2.067961
101          43.00          1            0.009709  2.077670
102          80.60          1            0.009709  2.087379

[103 rows x 4 columns]

In [12]:
from Univariate import univariate
qual,quan = univariate.QuanQual(dataset)
descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","Lesser_range","Greater_range","Min","Max"],columns=quan)

In [13]:
# Descriptive Function
def Descriptive_Table(dataset,quan):
    descriptive=pd.DataFrame(index=["Mean","Median","Mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5_Rule",
                                "Lesser_range","Greater_range","Min","Max"],columns=quan)
    for ColumnName in quan:
        descriptive[ColumnName]["Mean"] = dataset[ColumnName].mean()
        descriptive[ColumnName]["Median"] = dataset[ColumnName].median()
        descriptive[ColumnName]["Mode"] = dataset[ColumnName].mode()[0]
        descriptive[ColumnName]["Q1:25%"] = dataset.describe()[ColumnName]["25%"]
        descriptive[ColumnName]["Q2:50%"] = dataset.describe()[ColumnName]["50%"]
        descriptive[ColumnName]["Q3:75%"] = dataset.describe()[ColumnName]["75%"]
        descriptive[ColumnName]["99%"] = np.percentile(dataset[ColumnName],99)
        descriptive[ColumnName]["Q4:100%"] = dataset.describe()[ColumnName]["max"]
        descriptive[ColumnName]["IQR"] = descriptive[ColumnName]["Q3:75%"]-descriptive[ColumnName]["Q1:25%"]
        descriptive[ColumnName]["1.5_Rule"] = 1.5* descriptive[ColumnName]["IQR"]
        descriptive[ColumnName]["Lesser_range"] = descriptive[ColumnName]["Q1:25%"]-descriptive[ColumnName]["1.5_Rule"]
        descriptive[ColumnName]["Greater_range"] = descriptive[ColumnName]["Q3:75%"]+descriptive[ColumnName]["1.5_Rule"]
        descriptive[ColumnName]["Min"] = dataset[ColumnName].min()
        descriptive[ColumnName]["Max"] = dataset[ColumnName].max()
    return descriptive

In [14]:
dec = Descriptive_Table(dataset,quan)
dec

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5_Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [15]:
# Outliers function
def Outlier_Columns(descriptive,quan):
    Lesser_outlier = []
    Greater_outlier = []
    for ColumnName in quan:
        if descriptive[ColumnName]["Min"]<descriptive[ColumnName]["Lesser_range"]:
            Lesser_outlier.append(ColumnName)
        if descriptive[ColumnName]["Max"]>descriptive[ColumnName]["Greater_range"]:
            Greater_outlier.append(ColumnName)
    return Lesser_outlier,Greater_outlier

In [16]:
Lesser_outlier,Greater_outlier = Outlier_Columns(dec,quan)
Lesser_outlier

['hsc_p']

In [17]:
Greater_outlier

['hsc_p', 'degree_p', 'salary']

In [18]:
# Outlier handling function
def Replace_Outliers(Lesser_outlier,Greater_outlier,descriptive,dataset):
    for ColumnName in Lesser_outlier:
        dataset[ColumnName][dataset[ColumnName]<descriptive[ColumnName]["Lesser_range"]]=descriptive[ColumnName]["Lesser_range"]
    for ColumnName in Greater_outlier:
        dataset[ColumnName][dataset[ColumnName]>descriptive[ColumnName]["Greater_range"]]=descriptive[ColumnName]["Greater_range"]

In [19]:
Replace_Outliers(Lesser_outlier,Greater_outlier,dec,dataset)

In [20]:
Lesser_outlier = []   
Greater_outlier = []
for ColumnName in quan:
    if descriptive[ColumnName]["Min"]<descriptive[ColumnName]["Lesser_range"]:
        Lesser_outlier.append(ColumnName)
    if descriptive[ColumnName]["Max"]>descriptive[ColumnName]["Greater_range"]:
        Greater_outlier.append(ColumnName)

In [21]:
Lesser_outlier

[]

In [22]:
Greater_outlier

[]